apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskapi
  template:
    metadata:
      labels:
        app: taskapi
    spec:
      containers:
      - name: taskapi
        image: saguhildon/taskapi:2.1.0
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "31672"
---
apiVersion: v1
kind: Service
metadata:
  name: taskapi  
spec:
  type: NodePort
  selector:
    app: taskapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31500

